stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    
.rust_base:
  image: rust:latest
  cache:
    key: rustup
    paths:
      - .rustup/
  variables:
    RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add clippy

test_job:
  extends: .rust_base
  stage: test
  script:
    - cargo clippy --all --features full
    - cargo test --all --features full
    - cargo clippy --all
    - cargo test --all