[package]
name = "pt_config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A library for Rust-Based Pt config parsing"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive-deftly = { workspace = true }

## All errors
# Local development only
pt_err = { path = "../pt_err" }
# Use this when publishing to crates.io
# pt_err = { workspace = true }

# logs
# Local development only
pt_tracing = { path = "../pt_tracing" }
# Use this when publishing to crates.io
# pt_tracing = { workspace = true }

once_cell = { workspace = true }
dotenvy = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true}
envy = { workspace = true }
