[package]
name = "pt_config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A library for Rust-Based Pt config parsing"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
derive-deftly = { workspace = true }
# All errors
pt_err = { workspace = true, path = "../pt_err" }
# logs
pt_tracing = { workspace = true, path = "../pt_tracing" }
once_cell = { workspace = true }
dotenvy = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true}
envy = { workspace = true }
