[package]
name = "pt_config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true}
serde_json = { workspace = true}
toml = { workspace = true }
derive-deftly = { workspace = true }
pt_err = { path = "../pt_err" }
once_cell = { workspace = true }
dotenv = { workspace = true }
